### ISSUE TITLE
Implement mesh refinement

### ISSUE THREAD

**Issue by DanielVandH** [DanielVandH/DelaunayTriangulation.jl#30]
See Chap. 6 of Cheng, Dey and Shewchuk.

**Comment by juliohm** [comment]
Already implemented in Meshes.jl with different methods, see: https://juliageometry.github.io/Meshes.jl/dev/algorithms/refinement.html

**Comment by DanielVandH** [comment]
Do you have methods for meeting certain area/minimum angle constraints? The method I'm thinking of here is Ruppert's algorithm rather than just subdividing each triangle. I also want to eventually have extensions of Ruppert's algorithm, e.g. instead using off-centers or specialisations for domains with small angles.

This type of refinement is more useful in practice as far as I can tell. Another nice application I have in mind, and one I would use as an example when I finally get around to implementing this, is adaptive mesh refinement with _a posteriori_ error estimation for solving PDEs (see e.g. https://doi.org/10.1016/0377-0427(94)90290-9) to define area constraints on each triangular element.
